# Family Wise Error Rate calculations

Repository: https://github.com/ZainK-hub/satbinclass


In [9]:
5.0e-7 < 1.5e-6

True

In [11]:
import numpy as np
from scipy.stats import ttest_ind_from_stats
from statsmodels.stats.multitest import multipletests

### Table 2

In [120]:
mu_s = [
83.751,
83.403,
83.090,   
82.221,   
81.441,   
81.041,   
80.851,   
80.677,   
79.688,   
78.803,   
78.802,   
71.078,   
67.881,   
65.608,   
]
var_s = [
 1.503,
 1.341,
 1.271,
 0.846,
 1.285,
 1.310,
 5.161,
 2.355,
 2.954,
 1.403,
 1.579,
30.288,
24.456,
41.338]
nob_s = [20,]*len(var_s)

In [121]:
pval_s = [ttest_ind_from_stats(alternative='greater',
                               mean1=mu_s[0], std1=np.sqrt(var_s[0]), nobs1=nob_s[0],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [122]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True]),
 array([5.00000000e-01, 3.29165297e-01, 1.20689707e-01, 1.39220750e-04,
        9.46267917e-07, 4.87481236e-08, 3.07973275e-05, 8.63362438e-08,
        8.35632563e-10, 1.01030295e-14, 2.26485497e-14, 1.47859502e-11,
        1.55431223e-15, 3.54161145e-14]),
 0.0036571031913835705,
 0.0035714285714285718)

### Table 3

In [138]:
mu_s = [
84.862,    
84.672,
84.585, 
84.410,    
84.255,    
84.047,    
83.751,
83.595,
83.403,
83.090    
]
var_s = [
1.108,
1.350,
0.501,
0.848,
0.802,
0.908,
1.503,
0.811,
1.341,
1.271    
]
nob_s = [20,]*len(var_s)

In [139]:
pval_s = [ttest_ind_from_stats(alternative='greater',
                               mean1=mu_s[0], std1=np.sqrt(var_s[0]), nobs1=nob_s[0],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [140]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([False, False, False, False, False,  True,  True,  True,  True,
         True]),
 array([5.03680626e-01, 5.03680626e-01, 4.22972156e-01, 2.78235124e-01,
        1.34274823e-01, 4.21965387e-02, 1.35321375e-02, 8.62970231e-04,
        7.65962854e-04, 4.31224509e-05]),
 0.005116196891823743,
 0.005)

In [95]:
pval_s = [ttest_ind_from_stats(alternative='less', 
                               mean1=mu_s[6], std1=np.sqrt(var_s[6]), nobs1=nob_s[6],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [96]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([ True, False, False, False, False, False, False, False]),
 array([0.01545029, 0.06639284, 0.17246353, 0.23631827, 0.26139108,
        0.48729236, 0.75      , 0.75      ]),
 0.006391150954545011,
 0.00625)

### Table 4

In [129]:
mu_s = [
84.862,
84.723,
84.324,
84.063,
83.994,
83.751,
83.751,
83.472,
83.403,
83.090    

]
var_s = [
1.374,
1.690,
1.872,
1.739,
1.421,
1.503,
1.667,
1.224,
1.341,
1.271  
]
nob_s = [20,]*len(var_s)

In [130]:
pval_s = [ttest_ind_from_stats(alternative='greater',
                               mean1=mu_s[0], std1=np.sqrt(var_s[0]), nobs1=nob_s[0],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [131]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([False, False, False, False, False,  True,  True,  True,  True,
         True]),
 array([5.93247514e-01, 5.93247514e-01, 2.58387155e-01, 9.61475268e-02,
        6.26109787e-02, 1.98394930e-02, 2.09349821e-02, 1.72279025e-03,
        1.43009260e-03, 9.87291048e-05]),
 0.005116196891823743,
 0.005)

### Table 5

In [132]:
mu_s = [
84.775,
84.706,
84.497,
84.272,
84.115,
83.751,
83.403,
83.090 
]
var_s = [
1.464,
0.794,
0.829,
1.219,
1.254,
1.503,
1.341,
1.271 
]
nob_s = [20,]*len(var_s)

In [133]:
pval_s = [ttest_ind_from_stats(alternative='greater',
                               mean1=mu_s[0], std1=np.sqrt(var_s[0]), nobs1=nob_s[0],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [134]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([False, False, False, False, False,  True,  True,  True]),
 array([6.62666753e-01, 6.62666753e-01, 5.03913875e-01, 3.10779265e-01,
        1.87532651e-01, 3.37705399e-02, 2.64117898e-03, 2.09934512e-04]),
 0.006391150954545011,
 0.00625)

### Table 6

In [135]:
mu_s = [
84.862,
84.862,
84.775,
83.751,
82.640,
68.890,
68.784,
67.951,
66.390,
61.146,
60.628,
60.625,
59.965,
59.792,
59.549,
50.000,
50.000,   
]
var_s = [
1.108,
1.374,
1.464,
1.503,
1.700,
1.770,
0.897,
1.285,
6.151,
3.791,
2.901,
2.365,
1.233,
2.431,
2.256,
0.000,
0.000,
]
nob_s = [20,]*len(var_s)

In [136]:
pval_s = [ttest_ind_from_stats(alternative='greater',
                               mean1=mu_s[0], std1=np.sqrt(var_s[0]), nobs1=nob_s[0],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [137]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True]),
 array([7.89151426e-01, 7.89151426e-01, 7.89151426e-01, 7.75521839e-03,
        1.77497281e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00]),
 0.0030127052790058784,
 0.0029411764705882353)

### Table 7 K=10

In [144]:
mu_s = [
84.862,
84.862,
83.751,
70.522,
69.896,
67.760,
]
var_s = [
1.108,
1.374,
1.503,
4.619,
2.885,
0.891,
]
nob_s = [20,]*len(var_s)

In [145]:
pval_s = [ttest_ind_from_stats(alternative='greater',
                               mean1=mu_s[0], std1=np.sqrt(var_s[0]), nobs1=nob_s[0],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [146]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([False, False,  True,  True,  True,  True]),
 array([0.75      , 0.75      , 0.00582207, 0.        , 0.        ,
        0.        ]),
 0.008512444610847103,
 0.008333333333333333)

### Table 7 K=5

In [147]:
mu_s = [
85.139,
84.932,
83.507,
69.514,
69.237,
67.640,
]
var_s = [
1.012,
1.049,
1.774,
3.506,
5.901,
1.122,
]
nob_s = [20,]*len(var_s)

In [148]:
pval_s = [ttest_ind_from_stats(alternative='greater',
                               mean1=mu_s[0], std1=np.sqrt(var_s[0]), nobs1=nob_s[0],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [149]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([False, False,  True,  True,  True,  True]),
 array([5.00000000e-01, 4.54551603e-01, 1.38144455e-04, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]),
 0.008512444610847103,
 0.008333333333333333)

### Table 7 K=2

In [150]:
mu_s = [
85.330,
85.245,
83.423,
70.833,
70.228,
68.228,
]
var_s = [
0.427,
1.411,
2.764,
7.798,
0.703,
0.362,
]
nob_s = [20,]*len(var_s)

In [151]:
pval_s = [ttest_ind_from_stats(alternative='greater',
                               mean1=mu_s[0], std1=np.sqrt(var_s[0]), nobs1=nob_s[0],
                               mean2=mu_si,   std2=np.sqrt(var_si),   nobs2=nob_si).pvalue 
          for mu_si, var_si, nob_si in zip(mu_s[:],var_s[:],nob_s[:])]

In [152]:
multipletests(pval_s, alpha=0.05, method='holm-sidak')

(array([False, False,  True,  True,  True,  True]),
 array([6.28326781e-01, 6.28326781e-01, 4.02127131e-05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]),
 0.008512444610847103,
 0.008333333333333333)